#############################################################################
# Makefile for building: collidingmice
# Generated by qmake (2.01a) (Qt 4.7.0) on: niedz. pa? 17 14:01:28 2010
# Project:  collidingmice.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ -unix -o Makefile collidingmice.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -march=i686 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -march=i686 -mtune=generic -O2 -pipe -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,--hash-style=gnu -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mouse.cpp \
		object.cpp \
		window.cpp \
		player.cpp \
		projectile.cpp \
		customview.cpp \
		explosion.cpp moc_window.cpp \
		moc_customview.cpp \
		qrc_mice.cpp
OBJECTS       = main.o \
		mouse.o \
		object.o \
		window.o \
		player.o \
		projectile.o \
		customview.o \
		explosion.o \
		moc_window.o \
		moc_customview.o \
		qrc_mice.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		collidingmice.pro
QMAKE_TARGET  = collidingmice
DESTDIR       = 
TARGET        = collidingmice

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: collidingmice.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -unix -o Makefile collidingmice.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ -unix -o Makefile collidingmice.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/collidingmice1.0.0 || $(MKDIR) .tmp/collidingmice1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/collidingmice1.0.0/ && $(COPY_FILE) --parents mouse.h object.h window.h player.h projectile.h customview.h explosion.h .tmp/collidingmice1.0.0/ && $(COPY_FILE) --parents mice.qrc .tmp/collidingmice1.0.0/ && $(COPY_FILE) --parents main.cpp mouse.cpp object.cpp window.cpp player.cpp projectile.cpp customview.cpp explosion.cpp .tmp/collidingmice1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/collidingmice1.0.0/ && (cd `dirname .tmp/collidingmice1.0.0` && $(TAR) collidingmice1.0.0.tar collidingmice1.0.0 && $(COMPRESS) collidingmice1.0.0.tar) && $(MOVE) `dirname .tmp/collidingmice1.0.0`/collidingmice1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/collidingmice1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_window.cpp moc_customview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_customview.cpp
moc_window.cpp: ui_mainwindow.h \
		customview.h \
		mouse.h \
		object.h \
		player.h \
		window.h
	/usr/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

moc_customview.cpp: customview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) customview.h -o moc_customview.cpp

compiler_rcc_make_all: qrc_mice.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mice.cpp
qrc_mice.cpp: mice.qrc \
		images/stars.jpg \
		images/cheese.jpg \
		images/statek1.svg
	/usr/bin/rcc -name mice mice.qrc -o qrc_mice.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		customview.h
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mouse.h \
		object.h \
		window.h \
		ui_mainwindow.h \
		customview.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mouse.o: mouse.cpp mouse.h \
		object.h \
		window.h \
		ui_mainwindow.h \
		customview.h \
		player.h \
		explosion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mouse.o mouse.cpp

object.o: object.cpp object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o object.cpp

window.o: window.cpp window.h \
		ui_mainwindow.h \
		customview.h \
		mouse.h \
		object.h \
		player.h \
		explosion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

player.o: player.cpp player.h \
		object.h \
		window.h \
		ui_mainwindow.h \
		customview.h \
		mouse.h \
		projectile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

projectile.o: projectile.cpp projectile.h \
		object.h \
		window.h \
		ui_mainwindow.h \
		customview.h \
		mouse.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projectile.o projectile.cpp

customview.o: customview.cpp customview.h \
		window.h \
		ui_mainwindow.h \
		mouse.h \
		object.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o customview.o customview.cpp

explosion.o: explosion.cpp explosion.h \
		object.h \
		window.h \
		ui_mainwindow.h \
		customview.h \
		mouse.h \
		player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o explosion.o explosion.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_customview.o: moc_customview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_customview.o moc_customview.cpp

qrc_mice.o: qrc_mice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mice.o qrc_mice.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/ 
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/main.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/mouse.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/object.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/window.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/player.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/projectile.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/customview.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/explosion.cpp $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/mouse.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/object.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/window.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/player.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/projectile.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/customview.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/explosion.h $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/mice.qrc $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_FILE) /home/railis/projects/collidingmice_dominik/collidingmice.pro $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/
	-$(INSTALL_DIR) /home/railis/projects/collidingmice_dominik/images $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/main.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/mouse.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/object.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/window.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/player.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/projectile.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/customview.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/explosion.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/mouse.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/object.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/window.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/player.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/projectile.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/customview.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/explosion.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/mice.qrc 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/collidingmice.pro 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/images
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/doc/qt/examples/graphicsview/collidingmice/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

